# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: f5.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'f5.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66\x35.proto\x12\x03tts\"\x0c\n\nIsReadyMsg\" \n\x0fIsReadyResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"\x19\n\x06SayMsg\x12\x0f\n\x07message\x18\x01 \x01(\t\"+\n\x0bSayResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t21\n\x03TTS\x12*\n\x03Say\x12\x0b.tts.SayMsg\x1a\x10.tts.SayResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'f5_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ISREADYMSG']._serialized_start=17
  _globals['_ISREADYMSG']._serialized_end=29
  _globals['_ISREADYRESPONSE']._serialized_start=31
  _globals['_ISREADYRESPONSE']._serialized_end=63
  _globals['_SAYMSG']._serialized_start=65
  _globals['_SAYMSG']._serialized_end=90
  _globals['_SAYRESPONSE']._serialized_start=92
  _globals['_SAYRESPONSE']._serialized_end=135
  _globals['_TTS']._serialized_start=137
  _globals['_TTS']._serialized_end=186
# @@protoc_insertion_point(module_scope)
